{
  "active_arm": "right",
  "arms": {
    "left": {
      "base_link": "left_arm_base_link",
      "ee_link": "left_gripper_base_link",
      "joint_names": [
        "left_arm_joint1",
        "left_arm_joint2",
        "left_arm_joint3",
        "left_arm_joint4",
        "left_arm_joint5",
        "left_arm_joint6"
      ],
      "q_init": [-2.91, -0.83, -1.25, 1.58, 1.66, 3.66]
    },
    "right": {
      "base_link": "right_arm_base_link",
      "ee_link": "right_gripper_base_link",
      "joint_names": [
        "right_arm_joint1",
        "right_arm_joint2",
        "right_arm_joint3",
        "right_arm_joint4",
        "right_arm_joint5",
        "right_arm_joint6"
      ],
      "q_init": [-0.391495, 0.876906, 0.92, 1.55, 1.83, -3.54]
    }
  },
  "ik": {
    "damping": 0.12,
    "max_iterations": 140,
    "tol_pos": 0.0002,
    "tol_rot": 0.002,
    "max_step": 0.12,
    "min_step": 0.000001,
    "alpha": 1.0,
    "orientation_weight": 0.5
  },
  "elevator": {
    "joint_name": "elevation",
    "lower": 0.0,
    "upper": 0.8,
    "init":  0.3,
    "step":  0.005
  },
  "grippers": {
    "left": {
      "joint_names": [
        "left_gripper_l_joint1", "left_gripper_l_joint2", "left_gripper_l_joint3",
        "left_gripper_r_joint1", "left_gripper_r_joint2", "left_gripper_r_joint3"
      ],
      "coupling": [-1.0, -1.0, -1.0, 1.0, 1.0, 1.0],
      "max_angle": 1.0472,
      "step": 0.05
    },
    "right": {
      "joint_names": [
        "right_gripper_l_joint1", "right_gripper_l_joint2", "right_gripper_l_joint3",
        "right_gripper_r_joint1", "right_gripper_r_joint2", "right_gripper_r_joint3"
      ],
      "coupling": [-1.0, -1.0, -1.0, 1.0, 1.0, 1.0],
      "max_angle": 1.0472,
      "step": 0.05
    }
  },
  "keyboard": {
    "translation_step": 0.01,
    "rotation_step": 0.04
  },
  "server": {
    "host": "127.0.0.1",
    "port": 8765,
    "refresh_interval_ms": 40
  },
  "rm_api": {
    "enabled": false,
    "python_api_root": "third_party/RM_API2/Python",
    "ip": "192.168.1.18",
    "port": 8080,
    "thread_mode": "RM_DUAL_MODE_E",
    "log_level": 3,
    "speed_percent": 20,
    "blend_percent": 0,
    "connect": 0,
    "block": 0
  }
}
