{
  "active_arm": "right",
  "arms": {
    "left": {
      "base_link": "left_arm_base_link",
      "ee_link": "left_gripper_base_link",
      "joint_names": [
        "left_arm_joint1",
        "left_arm_joint2",
        "left_arm_joint3",
        "left_arm_joint4",
        "left_arm_joint5",
        "left_arm_joint6"
      ],
      "q_init": [-0.618126, -0.618649, -0.640780, -1.131288, 1.007701, 1.921154]
    },
    "right": {
      "base_link": "right_arm_base_link",
      "ee_link": "right_gripper_base_link",
      "joint_names": [
        "right_arm_joint1",
        "right_arm_joint2",
        "right_arm_joint3",
        "right_arm_joint4",
        "right_arm_joint5",
        "right_arm_joint6"
      ],
      "q_init": [0.618126, -0.618649, -0.640780, -1.131288, 1.007701, 1.921154]
    }
  },
  "ik": {
    "damping": 0.12,
    "max_iterations": 140,
    "tol_pos": 0.0002,
    "tol_rot": 0.002,
    "max_step": 0.12,
    "min_step": 0.000001,
    "alpha": 1.0,
    "orientation_weight": 0.5
  },
  "keyboard": {
    "translation_step": 0.01,
    "rotation_step": 0.04
  },
  "server": {
    "host": "127.0.0.1",
    "port": 8765,
    "refresh_interval_ms": 40
  },
  "rm_api": {
    "enabled": false,
    "python_api_root": "third_party/RM_API2/Python",
    "ip": "192.168.1.18",
    "port": 8080,
    "thread_mode": "RM_DUAL_MODE_E",
    "log_level": 3,
    "speed_percent": 20,
    "blend_percent": 0,
    "connect": 0,
    "block": 0
  }
}
